/*----- PROTECTED REGION ID(TargetTowerTangoServerClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        TargetTowerTangoServerClass.cpp
//
// description : C++ source for the TargetTowerTangoServerClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the TargetTowerTangoServer once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TargetTowerTangoServerClass.h>

/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass.cpp

//-------------------------------------------------------------------
/**
 *	Create TargetTowerTangoServerClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_TargetTowerTangoServer_class(const char *name) {
		return TargetTowerTangoServer_ns::TargetTowerTangoServerClass::init(name);
	}
}

namespace TargetTowerTangoServer_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
TargetTowerTangoServerClass *TargetTowerTangoServerClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::TargetTowerTangoServerClass(string &s)
 * description : 	constructor for the TargetTowerTangoServerClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
TargetTowerTangoServerClass::TargetTowerTangoServerClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering TargetTowerTangoServerClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::constructor

	cout2 << "Leaving TargetTowerTangoServerClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::~TargetTowerTangoServerClass()
 * description : 	destructor for the TargetTowerTangoServerClass
 */
//--------------------------------------------------------
TargetTowerTangoServerClass::~TargetTowerTangoServerClass()
{
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
TargetTowerTangoServerClass *TargetTowerTangoServerClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new TargetTowerTangoServerClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
TargetTowerTangoServerClass *TargetTowerTangoServerClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		loadConfigurationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *loadConfigurationClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "loadConfigurationClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->load_configuration(argin));
}

//--------------------------------------------------------
/**
 * method : 		homeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *homeClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "homeClass::execute(): arrived" << endl;
	return insert((static_cast<TargetTowerTangoServer *>(device))->home());
}

//--------------------------------------------------------
/**
 * method : 		abortClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *abortClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "abortClass::execute(): arrived" << endl;
	return insert((static_cast<TargetTowerTangoServer *>(device))->abort());
}

//--------------------------------------------------------
/**
 * method : 		alignClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *alignClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "alignClass::execute(): arrived" << endl;
	const Tango::DevVarULongArray *argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->align(argin));
}

//--------------------------------------------------------
/**
 * method : 		analyseClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *analyseClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "analyseClass::execute(): arrived" << endl;
	Tango::DevULong argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->analyse(argin));
}

//--------------------------------------------------------
/**
 * method : 		moveAbsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *moveAbsClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "moveAbsClass::execute(): arrived" << endl;
	const Tango::DevVarDoubleArray *argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->move_abs(argin));
}

//--------------------------------------------------------
/**
 * method : 		moveRelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *moveRelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "moveRelClass::execute(): arrived" << endl;
	const Tango::DevVarDoubleArray *argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->move_rel(argin));
}

//--------------------------------------------------------
/**
 * method : 		runClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *runClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "runClass::execute(): arrived" << endl;
	const Tango::DevVarULongArray *argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->run(argin));
}

//--------------------------------------------------------
/**
 * method : 		centerClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *centerClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "centerClass::execute(): arrived" << endl;
	const Tango::DevVarULongArray *argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->center(argin));
}

//--------------------------------------------------------
/**
 * method : 		clearConfigurationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *clearConfigurationClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "clearConfigurationClass::execute(): arrived" << endl;
	return insert((static_cast<TargetTowerTangoServer *>(device))->clear_configuration());
}

//--------------------------------------------------------
/**
 * method : 		disconnectClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *disconnectClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "disconnectClass::execute(): arrived" << endl;
	return insert((static_cast<TargetTowerTangoServer *>(device))->disconnect());
}

//--------------------------------------------------------
/**
 * method : 		saveImageClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *saveImageClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "saveImageClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<TargetTowerTangoServer *>(device))->save_image(argin));
}

//--------------------------------------------------------
/**
 * method : 		focusClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *focusClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "focusClass::execute(): arrived" << endl;
	return insert((static_cast<TargetTowerTangoServer *>(device))->focus());
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum TargetTowerTangoServerClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum TargetTowerTangoServerClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum TargetTowerTangoServerClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("TargetTowerTangoServer");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new TargetTowerTangoServer(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		TargetTowerTangoServer *dev = static_cast<TargetTowerTangoServer *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::attribute_factory_before
	//	Attribute : positionX
	positionXAttrib	*positionx = new positionXAttrib();
	Tango::UserDefaultAttrProp	positionx_prop;
	//	description	not set for positionX
	//	label	not set for positionX
	positionx_prop.set_unit("mm");
	//	standard_unit	not set for positionX
	positionx_prop.set_display_unit("mm");
	positionx_prop.set_format("%6.6f");
	//	max_value	not set for positionX
	//	min_value	not set for positionX
	//	max_alarm	not set for positionX
	//	min_alarm	not set for positionX
	//	max_warning	not set for positionX
	//	min_warning	not set for positionX
	//	delta_t	not set for positionX
	//	delta_val	not set for positionX
	
	positionx->set_default_properties(positionx_prop);
	//	Not Polled
	positionx->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(positionx);

	//	Attribute : positionY
	positionYAttrib	*positiony = new positionYAttrib();
	Tango::UserDefaultAttrProp	positiony_prop;
	//	description	not set for positionY
	//	label	not set for positionY
	positiony_prop.set_unit("mm");
	//	standard_unit	not set for positionY
	positiony_prop.set_display_unit("mm");
	positiony_prop.set_format("%6.6f");
	//	max_value	not set for positionY
	//	min_value	not set for positionY
	//	max_alarm	not set for positionY
	//	min_alarm	not set for positionY
	//	max_warning	not set for positionY
	//	min_warning	not set for positionY
	//	delta_t	not set for positionY
	//	delta_val	not set for positionY
	
	positiony->set_default_properties(positiony_prop);
	//	Not Polled
	positiony->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(positiony);

	//	Attribute : positionZ
	positionZAttrib	*positionz = new positionZAttrib();
	Tango::UserDefaultAttrProp	positionz_prop;
	//	description	not set for positionZ
	//	label	not set for positionZ
	positionz_prop.set_unit("mm");
	//	standard_unit	not set for positionZ
	positionz_prop.set_display_unit("mm");
	positionz_prop.set_format("%6.6f");
	//	max_value	not set for positionZ
	//	min_value	not set for positionZ
	//	max_alarm	not set for positionZ
	//	min_alarm	not set for positionZ
	//	max_warning	not set for positionZ
	//	min_warning	not set for positionZ
	//	delta_t	not set for positionZ
	//	delta_val	not set for positionZ
	
	positionz->set_default_properties(positionz_prop);
	//	Not Polled
	positionz->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(positionz);

	//	Attribute : positionP
	positionPAttrib	*positionp = new positionPAttrib();
	Tango::UserDefaultAttrProp	positionp_prop;
	//	description	not set for positionP
	//	label	not set for positionP
	positionp_prop.set_unit("mm");
	//	standard_unit	not set for positionP
	positionp_prop.set_display_unit("mm");
	positionp_prop.set_format("%6.6f");
	//	max_value	not set for positionP
	//	min_value	not set for positionP
	//	max_alarm	not set for positionP
	//	min_alarm	not set for positionP
	//	max_warning	not set for positionP
	//	min_warning	not set for positionP
	//	delta_t	not set for positionP
	//	delta_val	not set for positionP
	
	positionp->set_default_properties(positionp_prop);
	//	Not Polled
	positionp->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(positionp);

	//	Attribute : positionT
	positionTAttrib	*positiont = new positionTAttrib();
	Tango::UserDefaultAttrProp	positiont_prop;
	//	description	not set for positionT
	//	label	not set for positionT
	positiont_prop.set_unit("mm");
	//	standard_unit	not set for positionT
	positiont_prop.set_display_unit("mm");
	positiont_prop.set_format("%6.6f");
	//	max_value	not set for positionT
	//	min_value	not set for positionT
	//	max_alarm	not set for positionT
	//	min_alarm	not set for positionT
	//	max_warning	not set for positionT
	//	min_warning	not set for positionT
	//	delta_t	not set for positionT
	//	delta_val	not set for positionT
	
	positiont->set_default_properties(positiont_prop);
	//	Not Polled
	positiont->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(positiont);

	//	Attribute : deltaZX
	deltaZXAttrib	*deltazx = new deltaZXAttrib();
	Tango::UserDefaultAttrProp	deltazx_prop;
	//	description	not set for deltaZX
	//	label	not set for deltaZX
	//	unit	not set for deltaZX
	//	standard_unit	not set for deltaZX
	//	display_unit	not set for deltaZX
	//	format	not set for deltaZX
	//	max_value	not set for deltaZX
	//	min_value	not set for deltaZX
	//	max_alarm	not set for deltaZX
	//	min_alarm	not set for deltaZX
	//	max_warning	not set for deltaZX
	//	min_warning	not set for deltaZX
	//	delta_t	not set for deltaZX
	//	delta_val	not set for deltaZX
	
	deltazx->set_default_properties(deltazx_prop);
	//	Not Polled
	deltazx->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(deltazx);

	//	Attribute : deltaZY
	deltaZYAttrib	*deltazy = new deltaZYAttrib();
	Tango::UserDefaultAttrProp	deltazy_prop;
	//	description	not set for deltaZY
	//	label	not set for deltaZY
	//	unit	not set for deltaZY
	//	standard_unit	not set for deltaZY
	//	display_unit	not set for deltaZY
	//	format	not set for deltaZY
	//	max_value	not set for deltaZY
	//	min_value	not set for deltaZY
	//	max_alarm	not set for deltaZY
	//	min_alarm	not set for deltaZY
	//	max_warning	not set for deltaZY
	//	min_warning	not set for deltaZY
	//	delta_t	not set for deltaZY
	//	delta_val	not set for deltaZY
	
	deltazy->set_default_properties(deltazy_prop);
	//	Not Polled
	deltazy->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(deltazy);

	//	Attribute : cameraFeed
	cameraFeedAttrib	*camerafeed = new cameraFeedAttrib();
	Tango::UserDefaultAttrProp	camerafeed_prop;
	//	description	not set for cameraFeed
	//	label	not set for cameraFeed
	//	unit	not set for cameraFeed
	//	standard_unit	not set for cameraFeed
	//	display_unit	not set for cameraFeed
	//	format	not set for cameraFeed
	//	max_value	not set for cameraFeed
	//	min_value	not set for cameraFeed
	//	max_alarm	not set for cameraFeed
	//	min_alarm	not set for cameraFeed
	//	max_warning	not set for cameraFeed
	//	min_warning	not set for cameraFeed
	//	delta_t	not set for cameraFeed
	//	delta_val	not set for cameraFeed
	
	camerafeed->set_default_properties(camerafeed_prop);
	//	Not Polled
	camerafeed->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(camerafeed);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::pipe_factory_before
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::command_factory()
{
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::command_factory_before


	//	Command loadConfiguration
	loadConfigurationClass	*ploadConfigurationCmd =
		new loadConfigurationClass("loadConfiguration",
			Tango::DEV_STRING, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(ploadConfigurationCmd);

	//	Command home
	homeClass	*phomeCmd =
		new homeClass("home",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(phomeCmd);

	//	Command abort
	abortClass	*pabortCmd =
		new abortClass("abort",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pabortCmd);

	//	Command align
	alignClass	*palignCmd =
		new alignClass("align",
			Tango::DEVVAR_ULONGARRAY, Tango::DEV_BOOLEAN,
			"align x {0,1}, align y {0,1}",
			"",
			Tango::OPERATOR);
	command_list.push_back(palignCmd);

	//	Command analyse
	analyseClass	*panalyseCmd =
		new analyseClass("analyse",
			Tango::DEV_ULONG, Tango::DEV_BOOLEAN,
			"holder no",
			"",
			Tango::OPERATOR);
	command_list.push_back(panalyseCmd);

	//	Command moveAbs
	moveAbsClass	*pmoveAbsCmd =
		new moveAbsClass("moveAbs",
			Tango::DEVVAR_DOUBLEARRAY, Tango::DEV_BOOLEAN,
			"axis, distance",
			"",
			Tango::OPERATOR);
	command_list.push_back(pmoveAbsCmd);

	//	Command moveRel
	moveRelClass	*pmoveRelCmd =
		new moveRelClass("moveRel",
			Tango::DEVVAR_DOUBLEARRAY, Tango::DEV_BOOLEAN,
			"axis, distance",
			"",
			Tango::OPERATOR);
	command_list.push_back(pmoveRelCmd);

	//	Command run
	runClass	*prunCmd =
		new runClass("run",
			Tango::DEVVAR_ULONGARRAY, Tango::DEV_BOOLEAN,
			"axis, direction",
			"",
			Tango::OPERATOR);
	command_list.push_back(prunCmd);

	//	Command center
	centerClass	*pcenterCmd =
		new centerClass("center",
			Tango::DEVVAR_ULONGARRAY, Tango::DEV_BOOLEAN,
			"holder, sample",
			"",
			Tango::OPERATOR);
	command_list.push_back(pcenterCmd);

	//	Command clearConfiguration
	clearConfigurationClass	*pclearConfigurationCmd =
		new clearConfigurationClass("clearConfiguration",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pclearConfigurationCmd);

	//	Command disconnect
	disconnectClass	*pdisconnectCmd =
		new disconnectClass("disconnect",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pdisconnectCmd);

	//	Command saveImage
	saveImageClass	*psaveImageCmd =
		new saveImageClass("saveImage",
			Tango::DEV_STRING, Tango::DEV_BOOLEAN,
			"file path+name",
			"",
			Tango::OPERATOR);
	command_list.push_back(psaveImageCmd);

	//	Command focus
	focusClass	*pfocusCmd =
		new focusClass("focus",
			Tango::DEV_VOID, Tango::DEV_BOOLEAN,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pfocusCmd);

	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		TargetTowerTangoServerClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void TargetTowerTangoServerClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		TargetTowerTangoServer *dev = static_cast<TargetTowerTangoServer *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServerClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *TargetTowerTangoServerClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(TargetTowerTangoServerClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServerClass::Additional Methods
} //	namespace
