/*----- PROTECTED REGION ID(TargetTowerTangoServerStateMachine.cpp) ENABLED START -----*/
//static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        TargetTowerTangoServerStateMachine.cpp
//
// description : State machine file for the TargetTowerTangoServer class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <TargetTowerTangoServer.h>

/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::TargetTowerTangoServerStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  INIT     |  INITIALIZED
//  DISABLE  |  CONFIGURED
//  CLOSE    |  HOMING
//  STANDBY  |  READY
//  MOVING   |  MOVING
//  RUNNING  |  ALIGNING
//  OPEN     |  ANALYSING


namespace TargetTowerTangoServer_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_positionX_allowed()
 *	Description : Execution allowed for positionX attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_positionX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for positionX attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::positionXStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::positionXStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_positionY_allowed()
 *	Description : Execution allowed for positionY attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_positionY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for positionY attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::positionYStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::positionYStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_positionZ_allowed()
 *	Description : Execution allowed for positionZ attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_positionZ_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for positionZ attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::positionZStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::positionZStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_positionP_allowed()
 *	Description : Execution allowed for positionP attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_positionP_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for positionP attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::positionPStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::positionPStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_positionT_allowed()
 *	Description : Execution allowed for positionT attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_positionT_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for positionT attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::positionTStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::positionTStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_deltaZX_allowed()
 *	Description : Execution allowed for deltaZX attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_deltaZX_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for deltaZX attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::deltaZXStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::deltaZXStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_deltaZY_allowed()
 *	Description : Execution allowed for deltaZY attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_deltaZY_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for deltaZY attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::deltaZYStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::deltaZYStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_cameraFeed_allowed()
 *	Description : Execution allowed for cameraFeed attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_cameraFeed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for cameraFeed attribute in read access.
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::cameraFeedStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::cameraFeedStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_loadConfiguration_allowed()
 *	Description : Execution allowed for loadConfiguration attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_loadConfiguration_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::STANDBY ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::loadConfigurationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::loadConfigurationStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_home_allowed()
 *	Description : Execution allowed for home attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_home_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::STANDBY ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::homeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::homeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_abort_allowed()
 *	Description : Execution allowed for abort attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_abort_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::STANDBY)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::abortStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::abortStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_align_allowed()
 *	Description : Execution allowed for align attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_align_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::alignStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::alignStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_analyse_allowed()
 *	Description : Execution allowed for analyse attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_analyse_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::analyseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::analyseStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_moveAbs_allowed()
 *	Description : Execution allowed for moveAbs attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_moveAbs_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::moveAbsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::moveAbsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_moveRel_allowed()
 *	Description : Execution allowed for moveRel attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_moveRel_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::moveRelStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::moveRelStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_run_allowed()
 *	Description : Execution allowed for run attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_run_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::runStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::runStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_center_allowed()
 *	Description : Execution allowed for center attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_center_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::centerStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::centerStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_clearConfiguration_allowed()
 *	Description : Execution allowed for clearConfiguration attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_clearConfiguration_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::STANDBY ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::clearConfigurationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::clearConfigurationStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_disconnect_allowed()
 *	Description : Execution allowed for disconnect attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_disconnect_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::disconnectStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::disconnectStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_saveImage_allowed()
 *	Description : Execution allowed for saveImage attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_saveImage_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::saveImageStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::saveImageStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TargetTowerTangoServer::is_focus_allowed()
 *	Description : Execution allowed for focus attribute
 */
//--------------------------------------------------------
bool TargetTowerTangoServer::is_focus_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::INIT ||
		get_state()==Tango::DISABLE ||
		get_state()==Tango::CLOSE ||
		get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::OPEN)
	{
	/*----- PROTECTED REGION ID(TargetTowerTangoServer::focusStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::focusStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(TargetTowerTangoServer::TargetTowerTangoServerStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TargetTowerTangoServer::TargetTowerTangoServerStateAllowed.AdditionalMethods

}	//	End of namespace
